### ISSUE TITLE
MNK List

### ISSUE THREAD

**Issue by stgeke** [hfp/libxsmm#102]
Is it possible to provide an MNK list (containing all MxMs) to make?

**Comment by hfp** [comment]
I think you are asking for Issue #42 (perhaps the title of the issue is somewhat generic). Although rather trivial to support, the importance of the issue has de-emphasized with JIT code generation becoming the default, and hence the issue is still not implemented (but nicely aged).

Let's clarify: are you asking for some simple file format to be supplied (to `make`) in order to specify kernels, which are then generated statically (at build-time of the library)?

**Comment by stgeke** [comment]
Yes, that's what I am looking for.

**Comment by alheinecke** [comment]
just out of curiosity: why is the JIT compilation of the kernels not working/the best solution for you?
Thanks!

**Comment by hfp** [comment]
Side-note: v1.5.1 is around the corner. It will fix an issue with the Fortran interface in v1.5 (SMM functionality), where requesting a JIT kernel never returned a suitable PROCEDURE POINTER (always NULL).

**Comment by stgeke** [comment]
I don't like to sit in the queue on a big supercomputer to find out that something went wrong generating the kernels on the fly. Also, do you support KNC/KNL (including coprocessor configurations) with JIT?

**Comment by hfp** [comment]
We **do** support JIT code generation for KNL, and this just carries forward to KNL cards as well. However, we have not played with KNL cards so far. Generating JIT code for and on KNL is in production e.g., with CP2K.  
We do **not** support JIT code generation for KNC (neither native/self-hosted nor via offload); this is documented in our reference documentation.

**Comment by hfp** [comment]
Regarding "*I don't like to sit in the queue on a big supercomputer to find out that something went wrong generating the kernels on the fly.*" - Do you have anything that does not work for you, or is there anything we can do to improve something?
