### ISSUE TITLE
x86 build failure

### ISSUE THREAD

**Issue by loveshack** [hfp/libxsmm#103]
x86 is doubtless not very important, but I found a regression with it in 1.5.

Building v1.5 (or 1.5.1) for x86 with gcc 6 in i686 Fedora 24, using  STATIC=0 OMP=0 PREFETCH=1 SYM=1 SSE=0, fails with:

```
   /builddir/build/BUILD/libxsmm-1.5.1/src/libxsmm_timer.c:49:5: error: inconsistent operand constraints in an 'asm'
        __asm__ __volatile__ ("rdtsc" : "=a"(CYCLE), "=d"(libxsmm_timer_rdtsc_hi_)); \
        ^
   /builddir/build/BUILD/libxsmm-1.5.1/src/libxsmm_timer.c:79:3: note: in expansion of macro 'LIBXSMM_TIMER_RDTSC'
      LIBXSMM_TIMER_RDTSC(result);
      ^~~~~~~~~~~~~~~~~~~
```

In case you're interested, I'm looking at this with RPM packaging for inclusion in Fedora https://bugzilla.redhat.com/show_bug.cgi?id=1389016.

**Comment by hfp** [comment]
Thanks for reporting!
First of all, there is a quality goal sounding like "it should compile everywhere", which includes different tool chains (compilers, etc), different Linux distributions (perhaps "outdated"), and more. This goal mean that s the code is occasionally checked to compile on 32-bit platforms. However, the library does **not** support IA-32 in general! The latter is due to the calling convention of our JIT-generated code, which is exposed to support any particular calling convention (this is btw also the blocker for missing JIT support under Windows).

Having said 32-bit is not supported in general, there is still value to use this library on 32-bit platforms:
* Stand-alone out-of-place matrix transpose routines
* Statically generated SMM kernels
* Reference code for DNN
* etc.

However, I doubt that an i686 package should be provided, and I strongly recommend to **not** provide 32-bit packages (i686 or whatever it is called)!

**Comment by loveshack** [comment]
Thanks, and apologies that items are crossing here and on the package
review, where I'll note this.

**Comment by hfp** [comment]
As an exercise, I've fixed this in the master branch (though 32-bit remains unsupported, and very likely will not be supported ever).
