### ISSUE TITLE
libxsmm_gemm_prefetch2uid should return enum value of prefetch type

### ISSUE THREAD

**Issue by alheinecke** [hfp/libxsmm#116]
Right now libxsmm_gemm_prefetch2uid returns ascending numbers which are not aligned with the prefetch enum. This makes debugging hard and it's difficult to understand if the right type was chosen in the JIT dump. It would be better to return the enum value.

**Comment by hfp** [comment]
Well we have a bunch of environment variables, namely LIBXSMM_GEMM_PREFETCH and LIBXSMM_TILED_GEMM_PREFETCH, which can be set by the user. The whole purpose of the "uid" is to provide a contiguous range of number to select from. The uid is "documented" here: https://github.com/hfp/libxsmm/#generator-driver (look for the phrase "The prefetch strategy can be:"). The number shown on front of each strategy is just the UID. Though, it rather hard to use such environment variable otherwise since it would be an arbitrary number due to ORing POT-flags together. Anyhow, I should probably think about taking a character pointer i.e., the user interacts using the same string as the stand-alone gemm code generator.

However, I have improved the signature of these (internal) functions to take/get the enum type rather than converting int2int. I hope this makes it a bit safer.
