### ISSUE TITLE
libxsmm_gemm with trans arguments "T", "T"

### ISSUE THREAD

**Issue by kyungjoo-kim** [hfp/libxsmm#153]
I was testing the code with both tranA and transB = 'T' for the size of problems m = n = k = 5. 

Somehow the code is very slow. Do you have any reason that such case is not well optimized ?  

I check the other case with transA and B = 'N'. They are fast as expected.

**Comment by hfp** [comment]
Please have a look at https://github.com/hfp/libxsmm/wiki/Q&A#what-is-a-small-matrix-multiplication. Sorry this is not your fault, I just updated the Q&A as well as the reference documentation (incl. the PDF). These limitations have not been clearly communicated before. We are working at JIT'ted transpose routines (and hope to include these in 1.8.x [0<x]), which helps to overcome the *TransA* and *TransB* limitation.

To answer your question precisely, your code is falling back to BLAS i.e., whatever LAPACK/BLAS library you linked with.

**Comment by hfp** [comment]
What you can do (if it is all about batched matrix multiplication), you can use our stand-alone out-of-place matrix transpose routines and transpose the operands in question upfront. For batched transpose, you may rely on the non-OMP variants (libxsmm library) rather than the OpenMP-parallelized variants (libxsmmext library). Please also note, the aforementioned transpose routines are only fairly optimized and not CPUID-dispatched. However, LIBXSMM's static baseline code path (SSE4.2) is "good  enough", and CPUID-based dispatch would deliver much. The upcoming JIT'ted transpose will of course leverage all available instruction set extensions (if beneficial).

**Comment by hfp** [comment]
Moved this issue to https://github.com/hfp/libxsmm/wiki/Development#longer-term-issues (it will be addressed in the 1.8.x time frame).
