### ISSUE TITLE
Matrix-vector performance

### ISSUE THREAD

**Issue by eamartin** [hfp/libxsmm#157]
Does libxsmm have any support for gemv operations? Can libxsmm generate near optimal gemv code by generating gemm with N=1?

**Comment by hfp** [comment]
When you for example build the library with `make M=16 N=1 K=16 AVX=2`, you can inspect an assembly implementation which is equivalent to the in-memory generated JIT code (beside of dumping and disassembling the JIT code according to our reference documentation). What you can see is the minimum number of loads/stores, which is a first good sign (since GEMV is memory bound). LIBXSMM uses multiple microkernels (specific for each ISA extension), and a fixed scheme/heuristic to select a kernel. So yes, the GEMV code is reasonable.

**Comment by hfp** [comment]
https://github.com/hfp/libxsmm/wiki/Q&A#does-libxsmm-have-support-for-gemv
