### ISSUE TITLE
make test unconditionally rebuilds the library

### ISSUE THREAD

**Issue by rathann** [hfp/libxsmm#203]
In libxsmm-1.8.3 `make test` seems to rebuild the whole library unconditionally while it should only compile tests and run them and build the library only if it wasn't built already.

**Comment by hfp** [comment]
Is this under Windows (Cygwin or MinGW), or on an NFS share?

**Comment by hfp** [comment]
I have taken 1.8.3 from the release page (tar.gz), and I cannot reproduce this issue (neither for `make test` nor `make tests`). Please note, the standard test target is called `tests` (rather than `test`). Here is some background: [https://github.com/hfp/libxsmm/wiki/Validation](https://github.com/hfp/libxsmm/wiki/Validation).

Can you let me know what kind of (file-)system you are using?

I did the following:

```bash
make -j
  [...]
make
  make: Nothing to be done for 'libxsmm'.
make test
  [...]
  =============
  Running tests
  =============
  1 of 13 (atomics)... OK
  2 of 13 (blas)... OK
  3 of 13 (diff)... OK
  4 of 13 (gemmflags)... OK
  5 of 13 (hash)... OK
  6 of 13 (headeronly)... OK
  7 of 13 (malloc)... OK
  8 of 13 (matcopy)... OK
  9 of 13 (matdiff)... OK
  10 of 13 (mhd)... OK
  11 of 13 (otrans)... OK
  12 of 13 (threadsafety)... OK
  13 of 13 (vla)... OK
make test
  =============
  Running tests
  =============
  1 of 13 (atomics)... OK
  2 of 13 (blas)... OK
  3 of 13 (diff)... OK
  4 of 13 (gemmflags)... OK
  5 of 13 (hash)... OK
  6 of 13 (headeronly)... OK
  7 of 13 (malloc)... OK
  8 of 13 (matcopy)... OK
  9 of 13 (matdiff)... OK
  10 of 13 (mhd)... OK
  11 of 13 (otrans)... OK
  12 of 13 (threadsafety)... OK
  13 of 13 (vla)... OK
```

**Comment by hfp** [comment]
Thank you for the report!  Unfortunately, this issue may not fix for the next minor release since 1.8.4 is already under validation.

Please don't give up on reporting issues!  I woud like to keep any extra effort low for Linux package maintainers. You may consider to contribute the scripts used to build the RPMs (PR); perhaps I can accomodate larger changes upfront. Versoin 1.8.2 for instance changed the documentation structure (use index.md instead of copying README.md from root-folder), and 1.8.3 adjusted/fixed the soname (which is now [hopefully] more conforming).

**Comment by hfp** [comment]
Perhaps you can share some more details about the issue?  
Did it help to consider the key-value pairs for the test as well?

> The build system considers a set of given key-value pairs as a single unique build, and triggers a rebuild for any distinct set of flags.

( See also [here](https://github.com/hfp/libxsmm/issues/196#issuecomment-353115418) and [here](http://libxsmm.readthedocs.io/#classic-library-abi). )

I cannot reproduce such an issue (even not on NFS partitions); though there may be something like this when building on a Windows based file system.

**Comment by rathann** [comment]
Right, that was it. We (@loveshack and myself) have been calling `make`, `make install` and `make test` with different set of flags.

**Comment by hfp** [comment]
Thank you for the update!

**Comment by loveshack** [comment]
For what it's worth, I couldn't get the previous version run the test with the same set of flags but hadn't found time to look again.  I'm glad if it's fixed now -- thanks.
