### ISSUE TITLE
mkstemps() causes linker errors with glibc<2.7

### ISSUE THREAD

**Issue by geoffrey4444** [hfp/libxsmm#225]
In recent versions of libxsmm, libxsmm_trace.c and src/libxsmm_malloc.c call mkstemps(). 

This function only exists in versions of glibc since 2.7 (http://man7.org/linux/man-pages/man3/mkstemp.3.html), but I'm trying to link against libxsmm on an old cluster running RHEL 5, which only has glibc 2.5. So I get linker errors complaining that mkstemps is an undefined symbol.

The hardware I'm using is sufficiently old that upgrading is not feasible. Does this mean that I am stuck with version 1.5.2 of libxsmm, or is there a way to work around this problem?

If glibc 2.7 is a requirement, is there somewhere I could have seen this in the documentation? If so, please accept my apologies for missing it.

**Comment by hfp** [comment]
No you're not stuck. I will resolve this asap and you can rely on LIBXSMM/master (or a specific SHA/commit) until v2.0 is released.

**Comment by hfp** [comment]
For the time being (prior to v2.0), you may take any of the following (or the master revision):

* https://github.com/hfp/libxsmm/archive/580fd06301ea1c17662860a5ab6d1513a4deb9a2.tar.gz
* https://github.com/hfp/libxsmm/archive/580fd06301ea1c17662860a5ab6d1513a4deb9a2.zip

The revisions noted above shall fix the issue. Thank you for reporting!


**Note**: Needless to say that RHEL5 is well-agend with a lot of things that already need some maintenance e.g., an updated libssl in order to keep tools working [wget, curl, git]). It should be also noted that the default compiler (GCC v4.1) is below LIBXSMM's (official) baseline requirement. I am still maintaining compatibility with below-baseline (but without any claims).

**Comment by geoffrey4444** [comment]
Thank you very much for the quick response, @hfp! I was able to build the latest master branch. I'll watch for version 2.0 to go back to a stable release. I understand about RHEL5 being ancient, and I've already been hard at work updating many packages, including those you mention. I've installed GCC v7.3.0, which seems to be working well so far.

**Comment by hfp** [comment]
GCC v7.3 is a very reasonable choice; no issues from that side with LIBXSMM! Of course, the whole issue was just caused by an missing feature test on our end. Regarding stability, the SMM domain is stable and usually one can take our master if it says: ![Travis CI](https://travis-ci.org/hfp/libxsmm.svg?branch=master "Master branch build status"). I guess v2.0 is still some weeks away (if not two months).
