### ISSUE TITLE
Support Row Major?

### ISSUE THREAD

**Issue by zhcui** [hfp/libxsmm#226]
Dear developers,

I am writing a C++ code which uses libxsmm. However, I noticed that the convention is along with the BLAS, i.e. the matrix is assume to be column major order.  

I find some discussion in previous issue https://github.com/hfp/libxsmm/issues/80
But it looks like I have to make addtional transpose? 
Does the lib itself support row major dgemm just like CBLAS?

Thanks,
Zhihao

**Comment by hfp** [comment]
No the library does not support row-major by itself i.e., there is no CBLAS-like behavior. I alo think you can get around performing actual transposes since one can twiddle the GEMM arguments (or generate a kernel according to twiddled arguments):

gemm('N', 'N', m, n, k, alpha, a, lda, b, ldb, beta, c, ldc); // col-major
gemm('N', 'N', n, m, k, alpha, b, ldb, a, lda, beta, c, ldc); // row-major

Permuting the arguments is motivated by the following transpose identity C^T = A^T * B^T = (B * A)^T. You may wonder why CBLAS is not built-in since it seems an easy thing? This is because our kernels are natively column-major and we also want to encourage [manual dispatch](http://libxsmm.readthedocs.io/libxsmm_mm/#manual-code-dispatch) where the user (call-side) is ultimately exposed to unwrapped kernels.

Let me know if you have any problems and we can take a depper look!

**Comment by zhcui** [comment]
Thank you. It is true we can inverse the B and A to make it work.
Besides this, is the library able to work as a dynamical lib? I compiled a test file for gemm, like this,

`icpc 01_dgemm.cpp -mkl -I/home/zhcui/program/libxsmm_ZHC_installed/include -L/home/zhcui/program/libxsmm_ZHC_installed/lib/ -lxsmm -o 01_dgemm.out` 

When I try to run it `./01_dgemm.out`, it gives the link error,
./01_dgemm.out: error while loading shared libraries: libxsmm.so.1: cannot open shared object file: No such file or directory

In the folder, I do see the libxsmm.so and libxsmm.so.1 files.

Do you have any suggestions on it?

**Comment by hfp** [comment]
> Besides this, is the library able to work as a dynamical lib?

Yes. It's per `make STATIC=0` since only static libraries are built by default (`.a`). I think you already do this since you found something like `libxsmm.so`.

> In the folder, I do see the libxsmm.so and libxsmm.so.1 files.

You need to either set `LD_LIBRARY_PATH=/path/to/libxsmm/lib:$LD_LIBRARY_PATH` (per `export` or by prepending the environment variable when executing the program), or use `-Wl,--rpath=/path/to/libxsmm/lib` when you link your application. Using `exports` looks like:

```
export LD_LIBRARY_PATH=/path/to/libxsmm/lib:$LD_LIBRARY_PATH
ldd ./01_dgemm.out
  [...]
```

The above (`ldd`) will list all shared libraries (`[...]`) that your executable depends on. This will list something like "not found" if the LD_LIBRARY_PATH is insufficient. Of course, you can simply run your program and see that it works. Note that using the rpath linker flag embeds the library path into the executable such that is the library is "magically" found even without LD_LIBRARY_PATH. However, this is not appropriate when you plan to give the executable away to other people (who perhaps installed LIBXSMM somewhere else such that `/path/to/libxsmm` is different).

**Comment by zhcui** [comment]
Thanks. It works for me to set the LD_LIBRARY_PATH.

**Comment by hfp** [comment]
Thank you for trying!
