### ISSUE TITLE
Implement streaming stores

### ISSUE THREAD

**Issue by mkre** [hfp/libxsmm#25]
I want to call libxsmm functions for chunks of large matrices in a memory-bound kernel (similar to the "batched" mode in the examples).
Therefore, it would be great to have the possibility to employ streaming stores for the result matrix.

Is it possible/sensible/realistic that you implement this?

**Comment by alheinecke** [comment]
Currently, we don't have this on our list. However, we will keep this in mind and therefore I leave the issue open. A clean integration requires quite some work on the frontend side, especially for JIT as we can only issue streaming stores when C is vector length aligned and to support all architecture we will most likely require it to be 64byte aligned (to support SSE3-AVX512). Otherwise, you might streaming stores an arch A but not on B.

Can you share more details about your application (e.g. what are the matrix dimensions of C, can C be padded, etc.)

Thanks!

**Comment by mkre** [comment]
Thanks for the answer!

In this scenario, A and C are row-major and very tall and skinny (e.g., 1E7x16).
(Hence, B would be a 16x16 matrix in this case.)

C will be padded, such that each row is aligned.

**Comment by hfp** [comment]
We could probably attempt to quantify the performance impact of streaming stores for certain cases (your case). Since you want to store-away the result matrix, your case is also about BETA=0 which could trigger the streaming stores in a future implementation of LIBXSMM. Since your destinations are aligned, you can at least trigger generating aligned stores (ALIGNED_STORES=1).

**Comment by alheinecke** [comment]
(Ab)Using  BETA=0 for this is not a good idea since many applications require this for cache-level buffers which you definitely do not want to stream out. So it needs to be an option on top of BETA=0.

**Comment by hfp** [comment]
Moved this issue to https://github.com/hfp/libxsmm/wiki/Development#longer-term-issues.

**Comment by alheinecke** [comment]
done with this commit d0e6579
