### ISSUE TITLE
LIBXSMM in TensorFlow broken due to TensorFlow API changes

### ISSUE THREAD

**Issue by jewillco** [hfp/libxsmm#295]
It appears that changes in TensorFlow's `cpu_allocator` have caused LIBXSMM to no longer compile when used with TensorFlow. Although I am using an internal version of TensorFlow and an old version of LIBXSMM, the issues appear to likely be present in the current version as well. The interface for `tensorflow::cpu_allocator()` has changed recently (see the `tensorflow/core/framework/allocator.cc` changes in https://github.com/tensorflow/tensorflow/commit/7dea8383bbb97a1e78cdece876e083b22191974e) and that appears to break the forward declaration in `include/libxsmm_malloc.h`. There may not be a way to avoid having a TensorFlow `#include` in there now since the new default argument relies on a constant defined in another TensorFlow header.

**Comment by hfp** [comment]
Revision 22fa25dc4ad720f8f677153b939a05668c0618ff passes the regtest and benchmark for TF's sparse matmul-operator. There was the plain compilation issue due to the API change in TF plus an issue on LIBXSMM's side with library-initialization.

I will prepare a PR next day, or (if urgent) someone else may proceed without PR. LIBXSMM's next release will include the changes. However, for the time being 22fa25dc4ad720f8f677153b939a05668c0618ff should be fine.

Note: the conv-ops integration seems to be EOL or outdated, LIBXSMM gained a lot of functionality incl. fused ops (see issue #281).

**Comment by hfp** [comment]
Revision 8e74869e3360e785d163adb515a45476f5fb2598 contains addition fixes. Also, some (minor) changes in TF can enable LIBXSMM's Bfloat16 support for SpMDM:

```bash
git clone https://github.com/hfp/tensorflow-xsmm.git
git checkout upstream
git diff upstream..origin/master
```

Of course, the relevant changes must be taken (there are a lot more unrelated changes).

**Comment by hfp** [comment]
The TF-PR has been updated to ~current master but the merge is still pending. The PR will be updated once v1.11 is released (if it is still open by then). For LIBXSMM, the issue is resolved i.e., the change in TF's API is taken into account (5 months ago), and hence the issue here is closed (reoslved).
