### ISSUE TITLE
Use of uninitialised value in libxsmm_dispatch_trans()

### ISSUE THREAD

**Issue by oschuett** [hfp/libxsmm#298]
I ran valgrind and it  [reported](https://github.com/hfp/libxsmm/files/2717557/valgrind.txt) some use of uninitialised memory in `libxsmm_dispatch_trans()`.
Below is a short reproducer:
```
PROGRAM otrans_reproducer
   USE libxsmm, ONLY: libxsmm_otrans, libxsmm_ptr1, libxsmm_init, libxsmm_finalize
   USE iso_c_binding, ONLY: c_sizeof
   IMPLICIT NONE
   INTEGER            :: typesize
   REAL, DIMENSION(4) :: array_in
   REAL, DIMENSION(4) :: array_out
   array_in = 0.0
   array_out = 0.0
   typesize = c_sizeof(array_in(1))
   CALL libxsmm_init()
   CALL libxsmm_otrans(libxsmm_ptr1(array_out), libxsmm_ptr1(array_in), typesize, 2, 2, 2, 2)
   CALL libxsmm_finalize()
END PROGRAM
```

I compiled it like this;
```
gfortran -g otrans_reproducer.F90 -o otrans_reproducer.x -lxsmmf -lxsmm -lpthread -ldl -lblas
```

I'm using `libxsmm-1.10.0` as compiled by the [CP2K toolchain](https://github.com/cp2k/cp2k/blob/master/tools/toolchain/scripts/install_libxsmm.sh) and an Intel Ivy Bridge CPU (i5-3320M).

**Comment by hfp** [comment]
The issue should be suppressed/fixed in LIBXSMM/master, and the next bug-fix release will include the change. The problem was about partially initialized data (uninitialized part was not used), and hence it was a false positive detected by Valgrind. We use at least one technique to keep internal data definitions private e.g., our structures describing which code to generate (descriptor) uses an oversized array "blob" which is large enough to fit any descriptor (the actual descriptor is eventually smaller).

**Comment by hfp** [comment]
I checked using (equivalent to your reproducer):

```bash
make SYM=1 -j
cd samples/transpose; make SYM=1 -j
valgrind --track-origins=yes ./transposef o 2
```

**Comment by oschuett** [comment]
Thanks for the quick patch!
