### ISSUE TITLE
extracting common parts of sample makefiles

### ISSUE THREAD

**Issue by alheinecke** [hfp/libxsmm#30]
currently makefiles in the sample directories (smm, cp2k, nek) do not share a common configuration. Common parts should be carved out to make their maintenance easier.

**Comment by hfp** [comment]
I help with this issue, and bring up a solution which applies for Windows as well (it leverages GNU's make from either Cygwin or MINGW, and works for a Make-enabled CMD or Bash); I have something like this already. Right now, I am doing visual diffs (and edits) between the "cp2k" and "smm" code samples. For the time being, I can commit do this for other sample code as well (in order to have uniform Makefiles).

I have to admit that the Makefiles are a bit outgrown (while delivering good build-time features!) compared to their introduction time, however I do not want any "common" folder in the samples directory. I believe a self-contained sample folders are even preferred over replicating some text (Makefile content).

I suggest to bring up something like "Makefile.inc" (and perhaps "Makefile.rules") in addition to each of the Makefiles. The "Makefile.inc" (compiler detection and assembly of flags) will be an included prior to the sample-specific rules, and "Makefile.rules" might be a "post-include" to supply the actual build rules. Both files would be simply populated alongside of each Makefile.

**Comment by hfp** [comment]
Makefile.inc is now referenced by all Makefiles.

**Comment by hfp** [comment]
The Makefile.inc solution appears to be effectively reducing the amount of maintenance. Factoring out the build rules would go further but is very likely too specific (e.g. building sample code is quite different from the custom-build of LIBXSMM). Anything going beyond what is completed right now should be covered by a new issue (e.g., Linux/Windows cross-platform Makefile etc.).
