### ISSUE TITLE
building pkgconfig files still not right

### ISSUE THREAD

**Issue by loveshack** [hfp/libxsmm#333]
I still can't get the .pc files made correctly, but perhaps I'm doing it wrongly because I don't understand the directory variables and how to use them when building packages. I always get prefix= in the .pc file set to the staging area used by make install because DESTDIR and PREFIX aren't separate as in the autotools convention.  (No great problem, of course, as I just sed them.)

[Apologies if this is a patronizing explanation in case it's not clear!] For packaging it's convenient to be able to set the variables such that PREFIX is /usr (typically) and DESTDIR is the staging area into which the install is actually done (%buildroot for RPM builds, and a sub-directory for dpkg). Then paths in the installed files are under PREFIX, and DESTDIR shouldn't appear in them (which rpm checks). Is it possible to get that with the current make system somehow that I've missed?

**Comment by hfp** [comment]
No worries, I will bring a follow-on release shortly and thereby making another attempt to fix this problem.

**Comment by hfp** [comment]
I think what you want is to get the pkg-file's prefix set to PREFIX/DESTDIR even when not running `make install`. At this point, pkg's prefix is set to the staging folder but when you do `make PREFIX=/path/to/prefix  install`, it is properly set to the given PREFIX/DESTDIR. This would tell me, that when you build the package, `make install` is not invoked.

**Comment by hfp** [comment]
This is now hopefully fixed and targeted for v1.12. There is an updated documentation [here](https://libxsmm.readthedocs.io/#install-destdir) for DESTDIR, PREFIX, and DESTDIR vs. PREFIX. In addition, I have implemented PPKGDIR to set the location of the `.pc` files relative to the DESTDIR/PREFIX. For FreeBSD, PPKGDIR defaults to `libdata/pkgconfig` otherwise it defaults to `lib` as it was/is.
