### ISSUE TITLE
What is the difference between libxsmm-jit and libxsmm-static?

### ISSUE THREAD

**Issue by lingweiyang** [hfp/libxsmm#376]

**Comment by hfp** [comment]
In our documentation or other references (e.g., papers) we do not use terms like "libxsmm-jit" or "libxsmm-static". Can you please clarify what you are referring to? Meanwhile, let me guess what you could have meant.

* LIBXSMM can be built as a static library or as shared/dynamic library.
* LIBXSMM JIT-generates code for a number of function domains ("dynamic").
* LIBXSMM can generate SMM kernels at compile of the library ("static")
  and registers this code in the code-registry (similar/together w/ JIT-kernels).
  **Note**: this is a legacy feature used in the past to for instance account
  for the fact that LIBXSMM did not JIT-generate SSE kernels.
* The above legacy feature ("static kernels") can be combined with JIT-kernels
  both of which are registered in the same code-registry.
* LIBXSMM comes with a driver program (`libxsmm_gemm_generator`)
  that can generate assembly code that is printed into a filename of choice.

LIBXSMM can generate SSE kernels since then, and it is certainly legacy to register code which is generated at compile-time of the library. While it works for SSE and AVX/2/512, this is still unflexible since all kernel shapes must be specified at compile-time of LIBXSMM (`MNK`, `M`, `N`, `K` options for the make-line) plus this does not support leading dimensions (LDx) and only a common prefetch-kind. In addition, our code generation as well as querying it from the registry is very fast. If you work with batches of small multiplications, you should just ignore LIBXSMM's legacy. Further, all of the "static kernel" vs JIT discussion applies only to SMM. The latter is used by Deep Learning domain, true, but it is still not the way to go as the DL/DNN/CNN API cannot be utilized with static kernels.

I hope this helps already, but please let us know if your question was answered.
