### ISSUE TITLE
Performance is broken when using libxsmm_aligned_malloc, libxsmm_aligned_scratch

### ISSUE THREAD

**Issue by alheinecke** [hfp/libxsmm#383]
A recent performance study unveiled performance which were root-caused by the use of libxsmm_algined_malloc/libxsmm_algined_scratch for application based allocation. Switching to _mm_malloc improved the performance significantly.

This was observed for cnnlayer and running ResNet50 convolutions. 
`export OMP_NUM_THREADS=28`
`export KMP_AFFINITY=granularity=fine,compact,1,0`
`./run_resnet50.sh 28 100 1 f32 F L 1`
on a 8280 Cascade Lake CPU.

![perf](https://user-images.githubusercontent.com/6407923/81991645-9b680380-95f6-11ea-8854-0da47d2e8c41.png)

**Comment by hfp** [comment]
It's fixed and even better than `_mm_malloc`.

**Comment by alheinecke** [comment]
With the current master the performance is even slower than before.

**Comment by hfp** [comment]
The limit is dynamically exploiting the system. I will add verbose output for any such event and document it here.

Do you have a reproducer for a bad case?

**Comment by hfp** [comment]
Capturing the watermark and dynamically exploiting certain resource is implemented in a simplistic fashion (if not wrong). So, the issue is likely caused by that. Solution is in progress...

**Comment by hfp** [comment]
Certain allocation events are now shown at high verbosity levels, e.g., ```LIBXSMM WARNING: huge-page watermark reached at [...]``` (similarly for locked pages). Let aside huge-page partitioning, the limit for locked pages seems to be not reached on our cluster nodes (at least not by the tests that I checked). Please give it a (re-)try!

**Comment by alheinecke** [comment]
that was a machine not part of our cluster. The watermark returned an issue and reboot made the issue disappear.... So let's keep that issue in mind, but close it for now.

**Comment by alheinecke** [comment]
With the latest head GxM performance is reduce by 14% due to this issue. 
In samples/deeplearning/gxm:

source setup_env.sh
export OMP_NUM_THREADS=56
export KMP_AFFINITY=granularity=fine,compact,1,0
make clean && make -j 16
srun ./build/bin/gxm train model_zoo/resnet/1_resnet50_dummy_56_f32.prototxt model_zoo/resnet/solver.prototxt

**Comment by hfp** [comment]
I have to check this because we gained perf. from page-locked memory. However, it makes allocations itself much slower. In any case, the new verbose messages should provide watermark information when page-locked memory is exhausted (given it is enabled aka 8aee4b1). Thank you for the reproducer!

First step might be to limit page-locked memory allocation to scratch memory allocations as those can be amortized. I will also check if scratch memory allocations are abused for long-life and more regular memory buffers.

**Comment by alheinecke** [comment]
hmm... GxM does lazy allocations, however it excluded the first 2 iterations in the runtime measurement: https://github.com/hfp/libxsmm/blob/master/samples/deeplearning/gxm/src/Engine.cpp#L672

**Comment by hfp** [comment]
( I am getting certain to be off for 3 weeks; hope the best for the next two days ;-) 

The best you can do for this issue is to have a valid reproducer (command line), and target performamce vs. off-performance. With this information, I can drill-down and tune for the use case (if there is no other/general path). With current master we could even re-enable page-locked memory because it now only applies to scratch (and GxM uses just regular, i.e., non-scratch buffers).
