### ISSUE TITLE
Add density check to csr_asparse_reg?

### ISSUE THREAD

**Issue by mahudu97** [hfp/libxsmm#387]
For PyFR applications, using csr_asparse_reg, if the mesh is triangle/tetrehedra, the operator matrices have a density of over `0.5`. 

The fallback optimized dense routine is faster for those matrices than csr_asparse_reg, from my testing.

However, currently, due to supporting the number of unique non-zeros in the those denser matrices, csr_asparse_reg will be used, and so LIBXSMM will be slower than previous versions for those matrices.

Is it possible to have a check for density somewhere along the JIT path? Or is this more down to the user to know not to call a sparse routine if their matrix isn't particularly sparse?

**Comment by hfp** [comment]
There are PROS and CONS to do this. I can see that a user is forced to scan sparse data several times just to find out it is not suitable. Perhaps `libxsmm_create_xc*` routines can get an optional argument to take a threshold for such kind of density.

Since C has no optional arguments (other than variadic arguments), such an argument might be a pointer to a real number. There are several options to interpret such an argument, e.g., can be NULL to signify "automatic threshold" and still be non-NULL pointing to "0.0" to mean "no threshold". Of course, "automatic threshold" may be also `0.0`.

**Comment by alheinecke** [comment]
The code gen anyways scans the the sparse matrix, and we simply check from the CSR structure the density without scanning as B is dense and C is dense, so M, N, K are know and with one look up we have dense entries of A. 

So I suggest adding an argument here https://github.com/hfp/libxsmm/blob/master/src/libxsmm_fsspmdm.c#L142 and checking around here: https://github.com/hfp/libxsmm/blob/master/src/libxsmm_fsspmdm.c#L229 this value should be user provided.

**Comment by FreddieWitherden** [comment]
Just revisiting this.  As an alternative, we might want to consider having the routine attempt to JIT both a sparse and a dense kernel.  If both are successful then we can try benchmarking the routine on a temporary buffer and picking whatever is best.  Given all of the dimensions are known this should be relatively simple assuming libxsmm can provide us with some timing routines.

**Comment by alheinecke** [comment]
I think this is what you have submitted as a draft PR, correct?

**Comment by FreddieWitherden** [comment]
Yes, or at least a first pass.  Unlike a density check it does not need any heuristics.

**Comment by FreddieWitherden** [comment]
I believe this issue is resolved as of a few months ago with the merging of PR #473

**Comment by alheinecke** [comment]
OK, let me close it.
