### ISSUE TITLE
magazine.docx password

### ISSUE THREAD

**Issue by martin-schlossarek** [hfp/libxsmm#392]
Hi, 

within our company we synchronize EPEL repositories on a daily basis. Since libxsmm is part of EPEL 8, several packages from libxsmm end up in EPEL 8.

Within the libxsmm-doc RPM package there is a [magazine.docx](https://github.com/hfp/libxsmm/blob/master/samples/magazine/magazine.docx) with password protection. Since we (and many other big companies) have the requirement that all downloads have to go through a security proxy, we have a problem with the package: it contains a password protected file and thus this package is blocked because the password is unknown. 

Would it be possible to document the password for this file? What sense does it make to distribute an encrypted file?

**Comment by hfp** [comment]
Dear Martin,

thank you for reaching out and filing an issue!  
Would it help you to [exclude](https://github.com/hfp/libxsmm/blob/master/.gitattributes) such files from the Tarball?

> What sense does it make to distribute an encrypted file?

We have several encrypted files in our documentation directory as well. The `magazine.docx` in particular is our original document which was submitted for [https://software.intel.com/sites/default/files/parallel-universe-issue-34.pdf](https://software.intel.com/sites/default/files/parallel-universe-issue-34.pdf) and received some (minor) updates since then. Regarding the encrypted PowerPoint files (`*.pptm`) in the [https://github.com/hfp/libxsmm/tree/master/documentation](https://github.com/hfp/libxsmm/tree/master/documentation) folder, they do not contain secrets either but use some Intel slide-template (we avoid to spread) plus our collected and raw material for some talks (which may keep our talks more exciting plus it allows the hosting institution to be the exclusive source of a published talk/PDF).

**Comment by hfp** [comment]
Since our `make install` does not install any of the encrypted files, this issue might be something to be filed/complained with RHEL´s package maintenance. Please let me know if I should go ahead or if you want to do this.

**Comment by martin-schlossarek** [comment]
Hello Hans,

> Would it help you to exclude such files from the Tarball?

If this could be done, it would be the easiest and best way to prevent the distribution of encrypted files in RPMs (or other package formats). 
The other encrypted files you mentioned I can't find in the RPM package for EPEL/RHEL. The reason for this we see in the [RPM specfile](https://src.fedoraproject.org/rpms/libxsmm/blob/master/f/libxsmm.spec#_162):

```lang=rpm
%files doc
%doc README.md documentation/*.md documentation/*.pdf samples CONTRIBUTING.md
%license LICENSE.md
```

Only *.md and *.pdf are included - which is fine. But because the complete samples folder is included, the encrypted magazine.docx is also included.

**Comment by hfp** [comment]
Thanks again for your report!

**Comment by martin-schlossarek** [comment]
No problem and also thanks for the quick change!
