### ISSUE TITLE
xsmm should migrate to using Eigen::bfloat16

### ISSUE THREAD

**Issue by tjleeyon** [hfp/libxsmm#393]
bfloat16 is now part of Eigen; xsmm should migrate to using Eigen::bfloat16 instead of tensorflow::bfloat16.

**Comment by hfp** [comment]
Task: attempt to rely on zero-config (TF Bazel/build file for LIBXSMM).

**Comment by hfp** [comment]
I knew our integration with TF is essentially EOL and outdated. In fact, TF/master does not build with XSMM-knobs (since we revised our Deep Learning API since then). I may fix this aka "my last effort" (probably not). Potentially PlaidML's (plaidml-v1 branch) can revive TF+LIBXSMM even in a more thorough fashion (due to a TF-bridge being part of PlaidML).

@tjleeyon Are you interested in integrating Eigen and LIBXSMM? Or let me ask: what is your motivation for this PR and how can we potentially help?

**Comment by alheinecke** [comment]
Can we close this issue?

**Comment by hfp** [comment]
This issue is not current or not applicable anymore.
