### ISSUE TITLE
Alloc dealloc mismatch

### ISSUE THREAD

**Issue by seviezhou** [hfp/libxsmm#400]
## System info

Ubuntu X64, gcc (Ubuntu 5.5.0-12ubuntu1), libxsmm_gemm_generator (latest master [ea905d0](https://github.com/hfp/libxsmm/commit/ea905d08037e5d7869ceab057f7a310ccb9199f3))

## Command line

./bin/libxsmm_gemm_generator sparse foo.c foo 16 16 16 32 0 32 1 1 1 1 hsw nopf DP @@

## AddressSanitizer output

```
=================================================================
==9028==ERROR: AddressSanitizer: alloc-dealloc-mismatch (INVALID vs free) on 0x61300000de80
    #0 0x7fd31a8032ca in __interceptor_free (/usr/lib/x86_64-linux-gnu/libasan.so.2+0x982ca)
    #1 0x408d74  (/home/seviezhou/libxsmm/bin/libxsmm_gemm_generator+0x408d74)
    #2 0x402920  (/home/seviezhou/libxsmm/bin/libxsmm_gemm_generator+0x402920)
    #3 0x7fd31a1a483f in __libc_start_main (/lib/x86_64-linux-gnu/libc.so.6+0x2083f)
    #4 0x4035a8  (/home/seviezhou/libxsmm/bin/libxsmm_gemm_generator+0x4035a8)

0x61300000de80 is located 0 bytes inside of 340-byte region [0x61300000de80,0x61300000dfd4)
ASAN:SIGSEGV
==9028==AddressSanitizer: while reporting a bug found another one. Ignoring.
```

## POC

[alloc-dealloc-mismatch-libxsmm_gemm_generator-408d74.zip](https://github.com/hfp/libxsmm/files/5012243/alloc-dealloc-mismatch-libxsmm_gemm_generator-408d74.zip)

**Comment by hfp** [comment]
Thank you for reporting this issue!

( Just FYI, we make no promise regarding health of our master [although we continuously test our code even beyond the prominent Travis tests]. We treat our master-branch like a development branch and create releases at reasonable sync-points and with [hopefully] acceptable cadence. Let us know if this is not meeting your expectation so that we can rethink our QA. )

For our own records: are you relying on features in our master revision? It would be interesting to know! The main differentiation point of master vs. v1.16..1 at the moment are Intel Advanced Matrix Extensions.

**Comment by seviezhou** [comment]
Actually, I do not rely on the new features of the master branch, just think that the master is the newest one and I want to try it.

**Comment by hfp** [comment]
You are welcome, and it is much appreciated that you report your findings here!

The last we want is defects reported upstream first ("broken package") and causing all issue pages to echo/replicate a defect about a "broken" LIBXSMM. Also, libxsmm_gemm_generator is an example code that is like "legacy code" able to generate *static* code that is supposed to correspond with our JIT-generated code. We may need to remove this code-generator in the future since it is *exotic* rather than related to our intended use case.

**Comment by hfp** [comment]
You have used our static code generation and there were two cases of errors: (1) the requested kernel-shape did not match the given sparse input-data, and (2) the given input data was plain invalid/malformed (matrix market file header did not match data records). Our static code generation is "legacy functionality" and we do not intent to carry it forward. We completely embrace JIT-code generation.

Regarding the errors: we designed and implemented our code generation to deliver what the user requests ("WYSIWYG" with different perspective) and our API is not meant to perform deep validation and sanitation of user input. If you walk-in with fuzzed data, you can expect an error message at best. Also, LIBXSMM is quiet and intents to deliver error messages only when enabled (LIBXSMM_VERBOSE).

However, we strive to support our users to incorporate LIBXSMM and to deliver a reasonable amount of runtime error handling, which is the reason we fixed the reported issue. We would also like to learn about your application if any of the above statements made you nervous. Thank you for your report and your dedicated contribution!
