### ISSUE TITLE
How to enable amx?

### ISSUE THREAD

**Issue by ghjeong12** [hfp/libxsmm#403]
Hi, 

I am trying to compile a gemm code with amx instructions. I used the most recent clang version which is supposed to support amx. 
I set LIBXSMM_TARGET as spr, but the sample code in the repo still generates avx512 codes.

If you can provide a simple gemm code which will be translated into amx instructions, it would be really helpful to begin with.

Thanks in advance.

**Comment by alheinecke** [comment]
Can you specify what you mean with sample code? 

All deep learning primitives with BF16 will use AMX if the sizes fit and the sample/xgemm/kernel.c also uses AMX when the sizes fit.

**Comment by ghjeong12** [comment]
Thank you for the quick reply.

I tried sample/smm/, sample/hello/. I also tried to use /bin/libxsmm_gemm_generator to get amx instructions, but they only generated avx 512. According to your answer, maybe it's due to the data type or size doesn't fit. I just want to compile simple gemm code with amx to see how it will look like in the real binary file.

If I can just directly run xgemm/kernel to generate codes with amx instructions, could you give me the right arguments that I need to pass to _kernel_ (should be related to the sizes that fit, but I'm not sure what they should be)?

**Comment by alheinecke** [comment]
we don't support static code generation for AMX, all it just JIT, unless you use sde the code will not run.

./kernel 32 32 32 32 32 32 1 1 0 0 0 0 nopf BF16 nobr 1 1 1 

would use AMX

**Comment by ghjeong12** [comment]
Thank you for providing an example. So it will not generate amx instructions even though I manually change all 19 arguments into the constant in kernel.c and objdump the binary file?

**Comment by alheinecke** [comment]
don't know what you mean. What I shared generates AMX when target is SPR.

**Comment by ghjeong12** [comment]
Hmm.. I was asking since I coudn't see any amx insts after running objdump, but I could see many instructions marked as (bad). Maybe the clang that I'm using is the problem. Could you share which compiler version did you use for amx?

**Comment by alheinecke** [comment]
again, the compiler is irrelevant, the code is JIT'ed for AMX when kernel is running. Therefore, of course when objdumping the "kernel" there is not a single AMX instruction.

**Comment by ghjeong12** [comment]
I see, I may be misunderstanding the concept of jit compilation. Thank you for the clarification. As you mentioned, there is no way to get amx instructions from libxsmm as of now since it doesn't support static code gen, correct?

**Comment by hfp** [comment]
It seems you want to inspect the code that would be generated on a capable target?

You can do the following:

```bash
export LIBXSMM_TARGET=spr
export LIBXSMM_VERBOSE=-1
[ run some example code like Alex mentioned ]
objdump -D -b binary -m i386 -M x86-64 [JIT-dump-file]
```

I think `objdump` belongs to GNU Binutils. I doubt it can decode AMX instructions (at least as far as v2.34 goes).

**Comment by hfp** [comment]
Please note, the above mentioned flow of commands may only produce a single dumpfile corresponding to the first kernel requested by the sample code. This is because the sample code may attempt to run the kernel after requesting it, if so you need an AMX capable system (or SDE).

**Comment by alheinecke** [comment]
and LIBXSMM moves to JIT only for no feature. So we have no plan to add static code gen for AMX. But LIBXSMM has AMX suppoer, just through JIT though.

**Comment by hfp** [comment]
Feel free to open an issue in any case. Your contribution is welcome!

**Comment by ghjeong12** [comment]
Thank you for the response. In summary, objdumping the binary file itself will not give the amx instructions while objdumping jit-dump-file (which should be generated when I use JITDUMP=1) may generate amx instructions (If I'm wrong, please correct me). I will try to use the most recent objdump (both from llvm and gnu) and see whether they supports.

**Comment by ghjeong12** [comment]
`gcc  -D__BLAS=0 -DNDEBUG -D__STATIC=1 -DLIBXSMM_OPENMP_SIMD -DLIBXSMM_PERF -DLIBXSMM_PERF_JITDUMP -DLIBXSMM_BUILD=2  -Iinclude -I./src  -msse4.2 -fPIC -g -Wall -O2 -fopenmp-simd -funroll-loops -fdata-sections -ffunction-sections -fvisibility=hidden -pthread -c ./src/libxsmm_perf.c -o  obj/intel64/libxsmm_perf.o
./src/libxsmm_perf.c: In function 'libxsmm_perf_init':
./src/libxsmm_perf.c:145:3: warning: implicit declaration of function 'LIBXSMM_MEMZERO127' [-Wimplicit-function-declaration]
   LIBXSMM_MEMZERO127(&header);
   ^
./src/libxsmm_perf.c:151:23: warning: implicit declaration of function 'libxsmm_timer_tick' [-Wimplicit-function-declaration]
   header.timestamp  = libxsmm_timer_tick();
                       ^
./src/libxsmm_perf.c: In function 'libxsmm_perf_dump_code':
./src/libxsmm_perf.c:260:8: error: 'struct jitdump_record_code_load' has no member named 'internal_perf_codeidx'
     rec.internal_perf_codeidx = internal_perf_codeidx++;
`
I got the above error while I compile the library.. make JITDUMP=1 BLAS=0 OMP=0
Both from clang and gcc. Could you take a look at?

**Comment by hfp** [comment]
Will do, thank you for the report!

**Comment by hfp** [comment]
This is (hopefully) fixed and better tested now (LIBXSMM/master). The [log](https://github.com/hfp/libxsmm/commit/1229f65d365aafe818d8864d863437c017477e76) reads like "_Test at least compilation of Linux-perf facility. Updated Linux-perf facility for proper compilation. Please note: **we have not received maintenance for Linux perf facility since years**, and we maintain (and support) profiling JIT-code using Intel VTune Amplifier (https://libxsmm.readthedocs.io/libxsmm_prof/)._"

**Comment by hfp** [comment]
I overlooked some of your previous comments.

> jit-dump-file (which should be generated when I use JITDUMP=1)  [...] If I'm wrong, please correct me

The facility enabled by JITDUMP=1 (at compile-time) enables our support for "Linux Perf" (performance profiler). Dumping our JIT-code is way easier (no special build flags needed); see the earlier [comment](https://github.com/hfp/libxsmm/issues/403#issuecomment-669894685) (specifically, `LIBXSMM_VERBOSE=-1` is an environment variable/value which triggers the JIT-dump).

> I will try to use the most recent objdump (both from llvm and gnu) and see whether they supports.

Perhaps have a look at GNU Bintools (which is separate from GNU GCC version).

**Comment by ghjeong12** [comment]
Thanks for clarifying many points! I will try what you've suggested. 

In the mean time, I have a quick question. Do you know whether it is possible to run PIN with jit-code? In other words, the binary file xgemm/kernel can be directly used by PIN? I am curious since you've mentioned at some point to use Intel SDE, and it seems like it uses PIN internally.

**Comment by hfp** [comment]
> Do you know whether it is possible to run PIN with jit-code?

Yes, it is!  Please note, Pin generally does not depend on files in order to instrument code.

> In other words, the binary file xgemm/kernel can be directly used by PIN?

Pin performs code transformation and instrumentation in-memory (always), and naturally supports JITted code.

> I am curious since you've mentioned at some point to use Intel SDE, and it seems like it uses PIN internally.

Yes, Pin is internally used by Intel SDE. SDE replaces new instructions that would require certain CPU features (not available on actual execution target). In particular, SDE is used to test such code prior to hardware available.

**Comment by ghjeong12** [comment]
Thank you for the answer again!

I was able to get amx instructions generated from libxsmm by looking at SDE traces.
I want to compare the same gemm program under other old architectures like snb/hsw/skx, but it seems like I can only use skx. Others failed to finish jit (says JIT failed, please run with LIBXSMM_VERBOSE=-1 and/or with debug mode LIBXSMM library!).

I've used the following command as you suggested.
`
./kernel 32 32 32 32 32 32 1 1 0 0 0 0 nopf BF16 nobr 1 1 1
`

I guess the reason is that I need to use BF16 to exploit amx instructions while the architectures before skx do not support BF16. Am I guessing correct or is there any other way to compare different architectures?

**Comment by hfp** [comment]
> but it seems like I can only use skx

Bf16 is available by an [AVX-512 domain](https://software.intel.com/sites/landingpage/IntrinsicsGuide/#avx512techs=AVX512_BF16) and with upcoming Intel AMX. The AVX-512 also remains useful even with AMX for instance when performing type-conversions and quantization/rounding (copy-in/out). Bf16 support is present in "Cooperlake" (CPX), which is a recently released 4-socket platform. Please also note, VNNI is available since "Cascadelake" (CLX) and evolved out of KNM. Intel AMX resembles the important type-combinations (input+accumulator) as present with VNNI and AVX512/Bf16, i.e., int8-input and int32-accumulator for quantized data (common order of magnitude)), and Bf16-input with FP32-accumulator (individual magnitude by FP-element).

Rely on `LIBXSMM_TARGET` environment variable and try at least the following values: `clx` (VNNI), `cpx` (AVX512/Bf16), and `spr` (AMX). Regarding quantized integers (VNNI), you may have a look at question #408.

**Comment by ghjeong12** [comment]
@hfp Thanks to your help, I was able to play with gemm with amx instructions.
Can I ask you whether convolution operations in libxsmm also support amx instructions? If so, could you provide an example of something like this for convolution?

`./kernel 32 32 32 32 32 32 1 1 0 0 0 0 nopf BF16 nobr 1 1 1
`

**Comment by hfp** [comment]
@ghjeong12 LIBXSMM started with direct convolution kernels, i.e., specialized convolution kernels. However, our research and recent work transitioned LIBXSMM to "Deep Learning via a Single Building Block" (see the [1st reference](https://github.com/hfp/libxsmm/#references) for more details). This means convolutions are performed using a universal batch-reduce kernel which in turn is a small matrix multiplication (`C += A * B`). Since you already checked GEMM with AMX, you are very close (just replace `nobr` to get even closer).

**Comment by ghjeong12** [comment]
Thank you for the response. I thought since im2col is expensive, directly supporting convolution kernels would be more efficient. I will take a look at the reference you suggested. Could you also explain what nobr stands for?

**Comment by hfp** [comment]
I think im2col is a "standard methodology" and our work is not about im2col (otherwise I would not call it "research").

**Comment by hfp** [comment]
@ghjeong12 The `nobr` (your command line was `./kernel 32 32 32 32 32 32 1 1 0 0 0 0 nopf BF16 nobr 1 1 1`) stands for "no batch-reduce". What you want is batch-reduce, and there are several flavors (batches of SMMs can be specified with an array of pointers to matrices, indexes, etc.).

**Comment by hfp** [comment]
Very high level: integrating LIBXSMM´s convolutions (BR/batch-reduce) comes down to writing loop-nests related to the preferred format of your tensors, and then using BR inside of the loop-nest. We found that typical frameworks want to control the loop nest anyway and then relying on an highly optimized inner-most kernel comes in very handy. All the nasty corner/special cases with direct convolutions are gone for our kernel and also the loop nest becomes more focused (as it mostly deals with NHCW etc. permutations).
