### ISSUE TITLE
list option when pre-building the library

### ISSUE THREAD

**Issue by alheinecke** [hfp/libxsmm#42]
Currently, if a user wants to pre-build a specific set of specializations the MNK="" or M="", N="", K="" interface has to be used. For larger sets there have been reports that bash/make are failing and the entire build fails. It might be useful to have a python script, json, or xml input file which specifies the requested kernels and the LIBXSMM make system builds these kernels afterwards step-by-step.

**Comment by hfp** [comment]
The MM domain now supports SSE targets, which makes the static code generation a real legacy. This issue is unlikely to be taken (due to further reduced ROI). The only case where static code generation may help is with isolated kernel calls and when dispatch cost is predominant i.e., the dispatch overhead cannot be amortized.
