### ISSUE TITLE
Cache eviction policies and Hashing techniques used?

### ISSUE THREAD

**Issue by kaustubhcs** [hfp/libxsmm#458]
Would be of great help if you could help answer the following:

1. What is the eviction policy of the software cache (of the JIT compiler)?
2. How do you generate the keys (TAGS) to compare against, in your software cache? (Do you use CRC32 over the input parameters and CPUID?)
3. Is there a way to forcibly flush the software cache from the user side? (Any API to flush the software cache?)

**Comment by hfp** [comment]
Hi Kaustubh,

the cache is fully associative, i.e., size is also limited by (completely) searching the cache. Please note, this cache is on a per-thread basis (thread-local). The capacity as well as the size of the cache is always POT in order to optimize some of the operations (like eviction). The size can be smaller than the capacity (see paragraph at the bottom about `LIBXSMM_CACHE`).

1. Eviction is not based on additional counters such "least used". Instead, the one entry is evicted that is most distant from the last hit. It is sort of a round-robin/ring buffer policy.
2. CRC32 is used if permitted by the static architecture (target flag used when LIBXSMM is compiled), i.e., at least SSE4.2 was used. In past implementations, the CRC32-based hash was dispatched dynamically (can be easily reintroduced). However, SW based implementation is fully compatible with the HW implementation and highly/sufficiently tuned, i.e., dynamic dispatch is not used or the dispatch overhead is not worth the effort (at last according to my last check).
3. A `libxsmm_finalize`/`libxsmm_init` cycle could be abused to flush the cache of each thread. Actual flush can happen as part of this cycle or when the next dispatch discovers that the cache is not valid anymore (depends on what TLS is implementation is chosen). However, the fini/init cycle is costly as it includes unrelated stuff. Do you need an API for doing this? I can add if you can tell me more about your case.

There is an environment variable `LIBXSMM_CACHE` which can be also set to zero, which effectively disables the cache (without recompilation of LIBXSMM). Otherwise the size is set to the next larger-equal POT number (or the capacity at most). Further, the capacity can be set at compile-time `make CACHE=32` (`CACHE=0` disables the cache). The default capacity is 16 entries (like `CACHE=16`).

I am curious about your application and would like to hear more about your case or intention. You can also send a PM (if you prefer). There is also an [API](https://libxsmm.readthedocs.io/libxsmm_aux/#user-data-dispatch) to use the code registry (and hence the cache as well) for user-defined data, i.e., code registry can contain user-data.

**Comment by hfp** [comment]
It is perhaps of interest to have a look at the [Dispatch Microbenchmark](https://github.com/hfp/libxsmm/tree/master/samples/utilities/dispatch#dispatch). The results/output of calling `./dispatch.sh` is impacted by various settings such as `LIBXSMM_CACHE`. Please note, some of the timings (like time needed for first-time code gen.) are not only impacted by the CPU but also the OS like security-hardened environments (e.g., SELinux or virtualized environment).

**Comment by hfp** [comment]
The microbenchmark also allows to schedule a more limited set of kernels (by default it builds 10k kernels):

```bash
./dispatch.sh 8 4 1 4000000
```

The above only deals with 8 kernels (hence 1st time code-gen time is not a stable measurement), and it repeats 4000000 times exercising the cache hierarchy. In any case the microbenchmark reports the time fetching a kernel from cache as `dispatch (ro/cached)`, whereas `dispatch (ro)` is a cold-read going into the entire registry (no from cache). The category called `code-gen (rw)` reports the time needed to generate the code for the first time. The signs like `ro` and `rw` are with respect to accessing code registry under multiple threads (locking tries to permit multiple readers and a single writer).

**Comment by hfp** [comment]
For the record and for reference:

* **Code Generation**: LIBXSMM is a JIT assembler without textual frontend or such, i.e., there is an API to drive code generation. Code generation is very fast when compared to compiler based JIT infrastructure (e.g., LLVM-JIT). LIBXSMM does not have compiler phases and it does not use an Intermediate Representation (IR), i.e., machine code is assembled right away. Code generation takes in the order of 10s of Mikroseconds depending on CPU architecture and clock frequency, OS/environment, kernel parameters, etc.
* **Registry**: LIBXSMM’s JIT-code is persistent for the lifetime of an application (between libxsmm_init/finalize), and not meant to be deallocated. A JIT-code pointer therefore matches the behavior of normal/static functions, which are valid for the lifetime of an application. Such pointer can be copied (“shallow”) and kept around for whatever purpose and called at any time as needed by the application. The registry has an arbitrary capacity (e.g., 132k entries); it could be dynamically sized with little effort (the fixed size never posed a problem so far). A cold registry access takes in the order of 100 Nanoseconds.
* **Cache**: The cache is purely meant to accelerate the access to our registry. Evicting an entry from that cache does not mean the kernel is invalidated or deallocated. However, if you query that kernel again, it will take longer as the code registry is accessed ("cold access") rather than the thread-local cache ("hot access"). Beside of accelerating accesses, the cache is meant to be effective for application that use a limited set of kernels repeatedly. Our custom (user-)data registration can improve further if one registers a set of kernels that are always used together, then a single (cached) access occurs for multiple kernels which amortizes more favorable. A cache access (warm registry access) takes in the order of 10s of Nanoseconds.
* **Kernel**: The kernel is like a normal function pointer and cannot be inlined by the compiler (a call instruction is always necessary). The code size is typically not an issue, in fact our code is not unrolled to the maximum since we expect to partially operate on DRAM based operands/data, which makes it irrelevant if fully unrolled or not (note, if the same kernel is executed in a hot loop with same input, additional unrolling gives a false sense of better performance – or the other way said: who wants to compute the same result for the same input multiple times and consecutively?). Code size is hardly a problem (also with respect to the instruction cache of the CPU) although LIBXSMM wastes some memory since only multiples of full memory pages are allocated per each kernel. However, 4K pages are hinted for that purpose. Memory consumption can is shown using LIBXSMM_VERBOSE=<large positive number for most details>.
* **Introspection**: LIBXSMM implements code introspection in the sense of receiving the input that was leading to the code of a kernel (libxsmm_get_kernel_info, libxsmm_get_mmkernel_info [and for other kinds than just matrix multiplications “MM”, and also libxsmm_get_registry_info in general for the registry as a whole). Kernel information is inexpensive, i.e., can be received without searching the registry by providing the function pointer (kernel) as an input.

Further details: there is an API to deallocate a kernel but unless the library is compiled in a special fashion, the related function is not effective (it does nothing unless the registered kernel-kind is “user data”). There is no application deployed that expects or needs to deallocate a kernel. Also, deallocation would be API based and explicit and not like an automatic eviction. It is more user-friendly to keep all code around that was ever triggered during an application’s lifetime.
