### ISSUE TITLE
Missing prefetch options?

### ISSUE THREAD

**Issue by gallardjm** [hfp/libxsmm#461]
According to the documentation in libxsmm_be.md, there should be options to prefetch into L1:

```
10. "AL1": prefetch A' into L1 via accesses to A
11. "BL1": prefetch B' into L1 via accesses to B
12. "CL1": prefetch C' into L1 via accesses to C
13. "AL1_BL1": prefetch A' and B' into L1
14. "BL1_CL1": prefetch B' and C' into L1
15. "AL1_CL1": prefetch A' and C' into L1
16. "AL1_BL1_CL1": prefetch A', B', and C' into L1
```

However when trying to use them with the generator I get

```
wrong usage -> exit!


Usage (sparse*dense=dense, dense*sparse=dense):
    sparse, sparse_csr, sparse_csr_reg
    filename to append
    routine name
    M
    N
    K
    LDA (if < 1 --> A sparse)
    LDB (if < 1 --> B sparse)
    LDC
    alpha: 1
    beta: 0 or 1
    0: unaligned A, otherwise aligned (ignored for sparse)
    0: unaligned C, otherwise aligned (ignored for sparse)
    ARCH: noarch, wsm, snb, hsw, knl, knm, skx, clx, cpx
    PREFETCH: nopf (none), pfsigonly, other dense options fall-back to pfsigonly
    PRECISION: SP, DP
    matrix input (CSC mtx file)


Usage (dense*dense=dense):
    dense, dense_asm
    filename to append
    routine name
    M
    N
    K
    LDA
    LDB
    LDC
    alpha: -1 or 1
    beta: 0 or 1
    0: unaligned A, otherwise aligned
    0: unaligned C, otherwise aligned
    ARCH: noarch, wsm, snb, hsw, knl, knm, skx, clx, cpx
    PREFETCH: nopf (none), pfsigonly, BL2viaC, AL2, curAL2,
              AL2_BL2viaC, curAL2_BL2viaC,
    PRECISION: I16, SP, DP
```

And the options are not in the list of available ones.

I'm using the latest version: master-1.16.1-1252

The documentation seems to be quite old so maybe the options were removed since then?

**Comment by hfp** [comment]
Thank you for your report!

There was a cleanup wrt prefetch strategies, and the documentation might be outdated (libxsmm_be.md). I am sorry for this, I will take a look and match with the current implementation.

You probably read that the stand-alone generator is discouraged from use as it will not receive updates regarding future ISA extensions. I will let @alheinecke to jump in if your case is on a particular application like SeisSol. Anyhow, it would good to find a path using our API rather than the stand-alone generator. Let us know how we can help.

**Comment by gallardjm** [comment]
OK, then I assume there is no way to get prefetching to L1 or any prefetching of C' with the generator given the options supported by the generator?

I'm working on the ExaHyPE application (similar to SeisSol) and we are using the generator with our code generation to include the gemm in our single core compute kernels. We are using Loop-over-GEMM to perform tensor contraction operations, which I described briefly in this paper https://arxiv.org/pdf/2003.12787.pdf (section III-B), so prefetching the next tensor slice (=matrix) within the gemm was something I wanted to try out as we seem to be cache bound.

Here is an example of how we do the LoG with the gemm

```
for (int yz = 0; yz < 36; yz++) {
  gemm_16_6_6_gradQ_x_sck(lQi+yz*96, dudxT_by_dx, gradQ+yz*96);
}
```

Usually in our MM, B is a fixed coefficient matrix and we have sequential slices of our input and output tensor as A and C to process (with other data layouts we might need to have A as the coef matrix and B the input slice). 

I could always try to see if prefetching myself the next slices before calling the gemm using intrinsics is enough even if it most certainly will be less efficient than having the prefetching optimized inside the gemm code.

If we were to remove the call to the generator, is there a way to avoid JIT and get the production and compilation of the gemms at compile time? In our case every relevant MM parameter to set up a gemm is known and hard-coded before compilation.

**Comment by hfp** [comment]
This sounds a lot like our BRGEMM kernel (Batch-Reduce GEMM kernel), which is still a series of GEMMs (Beta=1). However, in contrast to prefetched singular GEMMs, it is meant for cases that are not exactly DRAM/memory bound. Looking at your pseudo-code, it appears you can just use our API for either case. You really want to avoid the stand-alone generator for above reasons (deprecated). If you argue about dispatch overhead, your code looks like it can dispatch a single kernel prior to the loop, and easily amortize the dispatch by running that same (and already dispatched) kernel repeatedly inside of the loop. With BRGEMM, you can perform perhaps some (if not all trips) as part of the kernel itself and solve your cache bottleneck.

For singular GEMMs, we have two dispatch flavors, a [weak/un-typed](https://github.com/hfp/libxsmm/blob/master/include/libxsmm.h#L136) variant (`libxsmm_xmmdispatch`) and [strong-typed](https://github.com/hfp/libxsmm/blob/master/include/libxsmm.h#L139) variants (e.g., for double-precision). There are tons of examples showing either variant including our [Hello LIBXSMM](https://libxsmm.readthedocs.io/#hello-libxsmm). For `libxsmm_xmmdispatch`, one can find the functions to build a descriptor [here](https://github.com/hfp/libxsmm/blob/master/include/libxsmm_generator.h#L23), and related flags are [here](https://github.com/hfp/libxsmm/blob/master/include/libxsmm_typedefs.h#L445).

The BRGEMM kernel however has some more prerequisites like input data format, e.g., whether indexes, pointers, strides, etc. There are strong-typed variants (see https://github.com/hfp/libxsmm/blob/master/include/libxsmm.h#L177 and many following lines), but I recommend to go for `libxsmm_xmmdispatch` (same as for singular GEMMs). It is just a matter of [building a descriptor](https://github.com/hfp/libxsmm/blob/master/include/libxsmm_generator.h#L23) requesting a BRGEMM rather than a GEMM-kernel (see [here](https://github.com/hfp/libxsmm/blob/master/include/libxsmm_typedefs.h#L445) to select from available flags). Perhaps the "kernel" sample (part of our [xgemm](https://github.com/hfp/libxsmm/blob/master/samples/xgemm/kernel.c) sample code) can help to estimate performance for your case (I am sorry for the command line interface ;-).

> If we were to remove the call to the generator, is there a way to avoid JIT and get the production and compilation of the gemms at compile time? In our case every relevant MM parameter to set up a gemm is known and hard-coded before compilation.

You could go lazy and just take the dispatch as you can expect it to be amortized (same kernel dispatched once per loop). Dispatch (as opposed to first time JIT code generation) takes in the order of tens of Nanoseconds (e.g., 50 ns) if you dispatch repeatedly from a limited set of kernels (we have a per-thread cache; see [here](https://github.com/hfp/libxsmm/issues/458#issuecomment-776521193) for details). If you need multiple different kernels inside of a loop, you can also [dispatch multiple kernels at once](https://libxsmm.readthedocs.io/en/latest/libxsmm_aux/#user-data-dispatch). **However**, your application just permits to have **no dispatch overhead** by simply dispatching the kernels you need during startup and then **keep** the function pointers around. Dispatch is only necessary if this upfront knowledge is not available. For example:

```c
int main(int argc, char* argv[])
{
  libxsmm_descriptor_blob blob;
  libxsmm_gemm_descriptor *desc = libxsmm_gemm_descriptor*(&blob, ...);
  /* function pointer kernel_16_6_6 remains valid for the lifetime of your application */
  libxsmm_xmmfunction kernel_16_6_6 = libxsmm_xmmdispatch(desc);
  ...
  /* you can call "kernel_16_6_6" whenever/wherever you want without JIT/disptach overhead */
}
```

**Comment by gallardjm** [comment]
I'll look into it then. I have been using the generator for 5 years and since the ExaHyPE project is almost over, it is probably something that will be used for ExaHyPE2. But I can try to see if we can do the switch easily in a proof of concept use case.

> You could go lazy and just take the dispatch as you can expect it to be amortized (same kernel dispatched once per loop). Dispatch (as opposed to first time JIT code generation) takes in the order of tens of Nanoseconds (e.g., 50 ns) if you dispatch repeatedly from a limited set of kernels (we have a per-thread cache; see here for details).

Just to be sure I understand you correctly. Once I have the descriptor, when I call the dispatch the first time JIT occurs but then the gemm compiled function stays cached and can be reused at no more cost than a function call the next time the dispatch is called inside the loop?

If yes would it stay cached if I call again at a later time my function using it, or not? Or do I need to set up a function pointer that will stay alive (for example in an object storing the ~10 gemm I need) as you propose?

My fear is that the matrices involved are already sometime very small (8x16 is typical on skx) so a JIT overhead could be significant. Furthermore the generator was really convenient as we already use code generation on our side to tailor the application toward a given architecture and setup so integrating the generated gemms is easy. We would probably lose a bit from going away from the generator (as we even use ``#pragma forceinline`` to even remove the function call overhead) but if we gain access to more complex and advanced configurations, in particular L1 prefetching, it could pay off.

**Comment by hfp** [comment]
> Once I have the descriptor, when I call the dispatch for the first time JIT occurs but then the gemm compiled function stays cached and can be reused at no more cost than a function call the next time the dispatch is called inside the loop. Is it right?

Jitted code is buffered for the lifetime of the application ("code registry"). We distinct "code generation" (initial dispatch; 10s of Mikroseconds) and "dispatch" (further we have "hot" and "cold"). If you keep the function pointer on your record, there is no need to ever dispatch it again. If you still do so (e.g., for convenience), you will not regenerate the code but receive already generated code from that code registry. Jitted code is like any other function pointer like one that refers to code generated by your regular compiler.

The only difference might be that an indirect call (via function pointer) cannot be inlined, whereas a function pointer that came from a statically compiled function might be inlined (if the compiler was able to track the value of the pointer, i.e., know which code it refers to). An indirect function call is also nothing to worry for these kernels since we talk about one additional instruction when compared to inlined code. In fact, it is likely your compiler does not inline, e.g., `gemm_16_6_6_gradQ_x_sck`.

Think of dispatch like a service that allows your to determine a function pointer that matches your call arguments. In your application you do not need this service, you can prepare a known set of function pointers upfront that match a fixed/known set of parameters/call arguments.

> If yes would it stay cached if later I call my function using it again, or not? Or do I need to set up a function pointer that will stay alive (for example in an object storing the ~10 gemms I need) as you propose?

The cache size (thread-local) can be configured at build-time (default size is 16 entries). However, the cache only gives you a lower dispatch time (10s of Nanoseconds) whereas storing/keeping them on your own is zero dispatch time (since you know which pointer you need to call).

**Comment by hfp** [comment]
I have updated our documentation. If any help is needed (now or later) for transitioning ExaHyPE away from the stand-alone generator, let me know. Again, thank you for reporting this issue!
