### ISSUE TITLE
bug in dfsspmdm related to memory allocation

### ISSUE THREAD

**Issue by semi-h** [hfp/libxsmm#501]
I'm having an issue with the latest version of libxsmm when using _dfsspmdm_ on Intel Xeon Platinum 8175M CPU. This is the error I got initially;
`double free or corruption (!prev)`
`Aborted (core dumped)`

with a debug build this is what I get;
```
python: ./src/libxsmm_main.c:400: __real_free: Assertion `free != libxsmm_malloc_fn.free.ptr' failed.
Thread 1 "python" received signal SIGABRT, Aborted.
__GI_raise (sig=sig@entry=6) at ../sysdeps/unix/sysv/linux/raise.c:51
51	../sysdeps/unix/sysv/linux/raise.c: No such file or directory.
```

I compiled libxsmm with GCC 10 and options STATIC=0 BLAS=0.

I think I've found the commit responsible from this. https://github.com/hfp/libxsmm/commit/5aca53b776c31cde525e2fd700d88c9c7e975cf2
At any point earlier than this everything works fine. Also, I don't get this error when using an Intel Core i7-4820K CPU,

**Comment by hfp** [comment]
Thank you for your report and bisecting the root cause!
I will look into this asap and report here.

**Comment by hfp** [comment]
This happens when following the recipe for PyFR+LIBXSMM?   
I am currently looking for a (simple) reproducer...

**Comment by semi-h** [comment]
Yes, this happens when I use PyFR with LIBXSMM. You can maybe try inc_cylinder example in PyFR v1.12.2. You don't need to change anything in the ini file, just do step 1 and step 3 from [here](https://pyfr.readthedocs.io/en/latest/user_guide.html#running-pyfr). I just tried this with Intel(R) Xeon(R) Platinum 8259CL CPU and it fails with the newest LIBXSMM but works fine with an earlier version.

**Comment by hfp** [comment]
> Yes, this happens when I use PyFR with LIBXSMM. You can maybe try inc_cylinder example in PyFR v1.12.2. You don't need to change anything in the ini file, just do step 1 and step 3 from [here](https://pyfr.readthedocs.io/en/latest/user_guide.html#running-pyfr). I just tried this with Intel(R) Xeon(R) Platinum 8259CL CPU and it fails with the newest LIBXSMM but works fine with an earlier version.

Thank you! This worked for me. For the record, I did the following (beyond installing PyFR):

```bash
cd PyFR/examples/inc_cylinder_2d
gunzip inc_cylinder_2d.msh
pyfr import inc_cylinder_2d.msh inc_cylinder_2d.pyfrm
pyfr partition 1 inc_cylinder_2d.pyfrm .
pyfr run -b openmp inc_cylinder_2d.pyfrm inc_cylinder_2d.ini
```

**Comment by hfp** [comment]
For debugging the problem, the following command was used:

```bash
gdb --args python3 ~/.local/bin/pyfr run -b openmp inc_cylinder_2d.pyfrm inc_cylinder_2d.ini
```

( The `LD_LIBRARY_PATH` may point to LIBXSMM's lib directory. )

**Comment by hfp** [comment]
I have applied a number of improvements for the fsspmdm code/driver incl. some (minor) fixes (the most "severe" was somewhat incorrectly calling `libxsmm_?mmdispatch` casting `LIBXSMM_GEMM_PREFETCH_NONE` to `const int*`). However, I noticed still issues even with replaced/debug memory allocations. The `libxsmm_?fsspmdm_create` corrupted memory related to running the benchmarks inside of this function. In particular, the benchmark of `k_sparse2` seemed to corrupt memory. The change a0852d8782c19adf918d4078044ef4f203d12e1c adjusted the kernel-width, which apparently fixed the problem. Another drawback of the previous implementation was about relying on `libxsmm_cpuid` rather than `libxsmm_get_target_archid`. The adjusted kernel-width may also fixed issue on systems without AVX-512. I have to test the latter, however, AVX2 systems previously produced an error only visible with `LIBXSMM_VERBOSE` (some high number).

**Comment by hfp** [comment]
> The adjusted kernel-width may also fixed issue on systems without AVX-512. I have to test the latter, however, AVX2 systems previously produced an error only visible with LIBXSMM_VERBOSE (some high number).

Running `LIBXSMM_VERBOSE=1 pyfr run -b openmp inc_cylinder_2d.pyfrm inc_cylinder_2d.ini` on a system without AVX-512 still produces an error like:

```text
LIBXSMM ERROR (libxsmm_generator_spgemm_csr_asparse_reg): invalid N blocking in microkernel (error #90016)!
```

**Comment by semi-h** [comment]
I just tried with the latest master and the problem is gone. Thanks.

**Comment by semi-h** [comment]
I've noticed a severe performance issue with the latest version. Could it be related to the changes here?

**Comment by hfp** [comment]
> I've noticed a severe performance issue with the latest version. Could it be related to the changes here?

There was one subtle change that came with a fix like:

```c
k_dense = libxsmm_dmmdispatch(N_dense, M, K, &ldb, &K, &ldc, &one, &beta, &flags, &prefetch);
```

which was previously:

```c
k_dense = libxsmm_dmmdispatch(N_dense, M, K, &ldb, &K, &ldc, &one, &beta, &flags, (const int*)LIBXSMM_GEMM_PREFETCH_NONE);
```

The original code for sure emerged from some misinterpretation of the interface and was not intentional. However, the effect was that the value behind `LIBXSMM_GEMM_PREFETCH_NONE` (0), was reinterpreted as a pointer (NULL). The latter meaning is "auto-prefetch" instead of "no prefetch".

I will change the current (fixed) code to perform auto-prefetch like before for the dense kernel.

**Comment by hfp** [comment]
Commit d7a077273a6dec5210b1bcddbde8920350284867 (re-)enables auto-prefetch for the dense kernel. Can you retry the new/current master revision?

**Comment by semi-h** [comment]
I tried the current master but the performance is still bad, there is no improvement. And I should say that the test case I'm running is using the sparse matrix multiplication, not the dense. The matrices has got less then 31 unique values.

**Comment by hfp** [comment]
Can you let me know the test case your are running?

**Comment by semi-h** [comment]
It is a Taylor-Green Vortex case with all hexahedral mesh. You can find the mesh file and the ini file in the link below
https://drive.google.com/drive/folders/1T4xZBiu0SMbuHq0D_5kKHQgcWqVadk-T?usp=sharing

I tried to recreate the issue with the examples provided in PyFR but becasue all the examples are 2D the difference in runtime is not big enough. With the test case I shared here runtime is around %50 more compared to an earlier libxsmm version.

**Comment by hfp** [comment]
Thank you for your help! Sorry for the confusion and the delay. The problem is finally solved and it is related to recently  introduced double-wide sparse kernels (14b6cea61376653b2712e3eefa72b13c5e76e421). In fact, even before, the code was maybe relying on random data like over-reading the stack. In essence this issue has nothing to do with memory allocation but memory corruption.

A follow-up investigation or feature request is perhaps needed since some tabulated/hard-coded data (permutation tables) are practically small in particular for the double-precision case like `libxsmm_dfsspmdm` (`libxsmm_sfsspmdm` seems to be fine). The outcome of the fix is that LIBXSMM is less likely to pickup a certain problem (fall-back into whatever PyFR implements in such case).

Note, the number of served/generated LIBXSMM-kernels can be shown with `LIBXSMM_VERBOSE=1` (or higher), which produces console output at the end of program execution/termination showing the number/kind of generated/served kernels.

**Comment by semi-h** [comment]
I think the problem is still there. I did a test with https://github.com/hfp/libxsmm/commit/14b6cea61376653b2712e3eefa72b13c5e76e421 as well and actually there is no performance issue at that stage.

**Comment by hfp** [comment]
> I think the problem is still there. I did a test with [14b6cea](https://github.com/hfp/libxsmm/commit/14b6cea61376653b2712e3eefa72b13c5e76e421) as well and actually there is no performance issue at that stage.

You mean the performance problem?  The memory corruption is resolved I think.

Indeed, 14b6cea61376653b2712e3eefa72b13c5e76e421 reads from uninitialized data like treating some array of tabulated (permutation table) values as A-matrix. In double-precision, this table only contains 64 elements, and M*N_sparse1 or even M*N_sparse2 can exceed 64 elements. As explained, the table for DP is (too) small now that proper conditions are in place. This can lead to LIBXSMM not used for certain/larger kernels which in turn can cause a performance penalty.

@alheinecke Can you take a look?

**Comment by semi-h** [comment]
> > I think the problem is still there. I did a test with [14b6cea](https://github.com/hfp/libxsmm/commit/14b6cea61376653b2712e3eefa72b13c5e76e421) as well and actually there is no performance issue at that stage.
> 
> You mean the performance problem? The memory corruption is resolved I think.

Yes, I mean the performance problem.

**Comment by alheinecke** [comment]
can you please share the assembly for the fast case (before all the changes many seem to be cosmetic but changing the logic on VLEN etc) and current master. It might be that some different code is generate and hence the performance is different. From this thread is not clear if this is AVX512 or AVX2 performance....

**Comment by hfp** [comment]
I said A-matrix above, but still did it wrong like MxN instead MxK. I will fix asap. Nevertheless, what's said about the permute-array is still true - SP-table is 256 entries, but DP-table only 64 elements. This limit must apply to incoming MxK.

**Comment by FreddieWitherden** [comment]
> I said A-matrix above, but still did it wrong like MxN instead of MxK. I will it fix asap. Nevertheless, what's said about the permute-array is still true - SP-table is 256 entries, but DP-table is only 64 elements (limit must apply to incoming MxK).

The sizes of the SP and DP permutation tables are not related to the matrix dimensions.  These tables are used in the sparse kernel generation when we run out of registers to hold the unique values of A.  Here, we put each unique value into its own vector lane (16 or 8 unique values per register).  The broadcasting is then done using the permutation tables (which are ideally stored in registers).  The single precision table is four times larger as we have two times as many possible values per register and these values need to be broadcast to two times as many vector lanes.

**Comment by hfp** [comment]
Commit 17dc1712f016222add18533e8fd0ada737775691 brings back the crashes... It still holds true that the wide sparse kernel (`k_sparse2`) somehow causes memory corruption.

**Comment by hfp** [comment]
> **Edit**: I guess I should also point out that the code also abuses the first argument of the JIT'ed function to pass a pointer to these tables (only used when they can not fit into registers). Just the easiest means of getting a pointer into the kernel.

Thank you! I will remove the conditions. Still, running `k_sparse2` in `libxsmm_?fsspmdm_create` seems to cause memory corruption.

**Comment by FreddieWitherden** [comment]
> > **Edit**: I guess I should also point out that the code also abuses the first argument of the JIT'ed function to pass a pointer to these tables (only used when they can not fit into registers). Just the easiest means of getting a pointer into the kernel.
> 
> Thank you! I will remove the conditions. Still, running `k_sparse2` in `libxsmm_?fsspmdm_create` seems to cause memory corruption.

Do you know what instruction in the generated kernel is going out of bounds?  This should make it relatively simple to track down the issue.  And in what 'branch' (constants broadcast in registers, constants packed in registers w/permutes in registers, constants packed in registers with permutes from memory)?  The latter is the only one which accesses 'A' (https://github.com/hfp/libxsmm/blob/master/src/generator_spgemm_csr_asparse_reg.c#L398).

**Comment by hfp** [comment]
@FreddieWitherden I am foreign to the fsspmdm-code and have no insight so far. I just adopted the case because of potentially "related to memory allocation". It does not seem to be related to memory allocation but memory corruption. I disabled generating the k_sparse2-kernel, which seems to fix the crashes.

**Comment by hfp** [comment]
Let me close this issue. The crashes are resolved at no performance impact when compared to the previous release (1.16.1). However, we lost the contribution of the double-wide sparse kernel which seems to be related to memory corruption and the problem needs its own issue and investigation.
