### ISSUE TITLE
Why libxsmm is faster than Eigen in small matrix multiplication?

### ISSUE THREAD

**Issue by jhss** [hfp/libxsmm#507]
I would like to know why libxsmm is faster than Eigen in SMM.

I read your paper, but I don't fully understand why it is faster.

I understand that libxsmm generate sepecialized code for SMM, therefore it is faster.

Is it right?

**Comment by hfp** [comment]
Yes, this can be one source of an advantage. Though, LIBXSMM's kernels are specialized, i.e., hard-coded for the specific properties of the matrix-multiplication. The term "hard-coding" is normally not a positive property if it impairs limitations when using such kernels. However, LIBXSMM generates specialized code at runtime of an application (Just-In-Time) to maintain flexibility. Also, LIBXSMM does not support all kinds of a general GEMM operation like Alpha and Beta arguments are restricted. Further, for a series of small matrix multiplications ("batch"), it is possible to explicitly prefetch operands (e.g., the small matrices) which is beneficial if operands are not in a predictable order (CPU's automatic prefetch cannot consistently figure out the next operands). Obviously, the latter applies mostly when reading operands from DRAM rather than artificially benchmarking a "hot loop" (in-cache). Care must be taken when benchmarking or claiming advantages; it matters to accurately model the real application properly and in a reproducible fashion.

**Comment by hfp** [comment]
Thank you for your question!

I am assuming your question is sufficiently answered. If this is not the case, feel free to reopen or open a new issue.
