### ISSUE TITLE
forced MPSS dependency when compiling

### ISSUE THREAD

**Issue by sheng-li** [hfp/libxsmm#60]
installed libxsmm with vanilla make install. Then when compiling programs using libxsmm,  it complaint with:  catastrophic error: *MIC* cannot open source file "cstdlib"

**Comment by alheinecke** [comment]
can you please provide your source file and the compile line?

**Comment by alheinecke** [comment]
The error causing compile line is:

icpc -O2 -openmp -DNDEBUG test_libxsmm_simple.cpp -I$LIBSXMM_HOME/include/ -L$LIBXSMM_HOME/lib -lxsmm -o test_libxsmm


with this being the content of test_libxsmm_simple.cpp:

#include <cstdlib>
#include <iostream>
#include <libxsmm.h>
#include <libxsmm_timer.h>

int main(int argc, char* argv[]) {
  libxsmm_init();
  const libxsmm_mmfunction<float> xmm(32, 32, 32);

  if (!xmm) { // specialized routine
          std::cout << "failed to jit " << std::endl;
          exit(0);
  }
}

**Comment by hfp** [comment]
There is **no issue** with this code except that it misses to supply `-no-offload` (or `-qno-offload`) on the compiler's command line. This "problem" is caused by the Intel Compiler which is automatically enabling the hybrid offload build (two-phase compilation) if a target/mic attribute is discovered in the code (LIBXSMM_RETARGETABLE i.e., `__attribute__((target(mic)))`). The latter requires MPSS being installed, or induces the need to turn off the two-phase compilation.

For the Fortran side, we do weed-out the target attributes if no offload build is performed. The latter is overcoming the above inconvenience. I can see no reason to not apply this technique to the C/C++ side. One of the soon/next upcoming commits will get rid of this inconvenience.

**Comment by alheinecke** [comment]
yes it's just about the inconvenience. I got several reports over email about this and it's not documented. So guarding offload extensions should increase ease of use.
