### ISSUE TITLE
Link behavior changed, cannot longer link to without OpenMP when library was built using OpenMP

### ISSUE THREAD

**Issue by alheinecke** [hfp/libxsmm#66]
Latest changes introduce a hard OpenMP dependency. Can we get this under control by splitting the medium-sized gemm into a different library which depends on libxsmm?

**Comment by hfp** [comment]
This issue is related to #65 and it will be resolved by dedicating the former link-time wrapper library (libxsmmld) to an "extension library" which is covering "non-core functionality". The definition of "non-core" is related to the (in-)availability of functionality depending on the platform and/or other conditions.

**Comment by hfp** [comment]
CI passes with the fix implemented. As a last comment before closing: the issue was known at the time of enabling OpenMP along with issue #65, however the development is (fortunately) still driven by request rather than arguing about legacy.
