### ISSUE TITLE
determining LIBXMM's target arch

### ISSUE THREAD

**Issue by alheinecke** [hfp/libxsmm#68]
Can we add a function, e.g. libxsmm_get_target_arch() which returns vector instruction the JIT compilation will generator code for. I suggest exposing 

/* defining instruction sets */
#define LIBXSMM_X86_SSE3                  1000
#define LIBXSMM_X86_AVX                   1001
#define LIBXSMM_X86_AVX2                  1002
#define LIBXSMM_X86_IMCI                  1003
#define LIBXSMM_X86_AVX512                1004

from generator_common.h as enum in libxsmm_typedef.h

**Comment by hfp** [comment]
Unfortunately the collection of target architectures has to remain in the preprocessor's realm due to the fact that enum values cannot be involved into conditional compilation (#if). However, it is desirable to involve them into such expressions in particular related to LIBXSMM_STATIC_TARGET_ARCH and LIBXSMM_MAX_STATIC_TARGET_ARCH (see libxsmm_intrinsics_x86.h).

**Comment by alheinecke** [comment]
Can we add functions supporting this as this is needed/beneficial in user code?
