### ISSUE TITLE
DBG=2 option seems to be not working with GCC

### ISSUE THREAD

**Issue by alheinecke** [hfp/libxsmm#83]
When compiling LIBXSMM with:
make CC=gcc CXX=g++ FC=gfortran DBG=2
I'm seeing tons of these errors when linking libxsmm:
~/libxsmm_github/src/libxsmm_gemm.c:122: undefined reference to `__tsan_read4'
~/libxsmm_github/src/libxsmm_gemm.c:122: undefined reference to `__tsan_write4'
~/libxsmm_github/src/libxsmm_gemm.c:123: undefined reference to `__tsan_read4'
~/libxsmm_github/src/libxsmm_gemm.c:123: undefined reference to `__tsan_read4'
~/libxsmm_github/src/libxsmm_gemm.c:123: undefined reference to `__tsan_write4'

**Comment by hfp** [comment]
Using the GCC tool chain appears to link fine (at least with recent versions), but at runtime the message "FATAL: ThreadSanitizer: unexpected memory mapping" appears. Most often the suggestion is to compile with -fPIE, and to link with -pie. However, this is a distracting recommendation both in terms of more recent TSan requirements as well as the actual practice with LIBXSMM's compile/link stages. It turns out that libtsan is just missed from the link line (which is more in line with your report). Apparently, GCC does less magic when -fsanitize=thread is applied to the link-line (in fact it appears to ignore this flag). So, -fsanitize=thread seems to be useless when using GCC as a linker driver and -ltsan is what is needed. I've just implemented the latter (in addition to what's in place already). So with Clang, -ltsan is likely superfluous at link-line whereas with GCC the -fsanitize=thread does nothing when added to the link-line... I think the confusion comes from "solutions" that do not distinct between compile and link stage i.e., using whatever compiler (GCC/Clang) with a one-step compile/link works, but having it separately just works differently when comparing the aforementioned tool chains.

**Comment by hfp** [comment]
This issue is not fully fixed, but another attempt was spent on trying to improve the situation. At this point, it might be only portable and flawless with special-casing not only for the tool chain (GCC, Clang) but also for the different versions along these tool chains. I believe it's not worth the effort, and one might fix his own use case locally. Otherwise, Intel Inspector might be an alternative, which works flawless and with little to no false positives.
