### ISSUE TITLE
A few doubts

### ISSUE THREAD

**Issue by sidkashyap** [hfp/libxsmm#99]
I just started using libxsmm - I had the following queries, any help is much appreciated

1) OpenMP support: I am invoking the libxsmm_sgemm_omp routine with LIBXSMM_MT=1/2, the code does not look to be scaling beyond a thread. I debugged to verify that it is indeed calling the tile routine. Are there any best practices around this?

2) Fallback to MKL: What is the behaviour of the the code for gemm calls that are bigger than 80 (>300 actually) which are captured through LD_PRELOAD, what is the dependency on MKL? Can you please  confirm the scenarios under which it invokes MKL?

Regards,
Sid

**Comment by alheinecke** [comment]
1) do you have the problems with the sample or with your own code?

2) for all cases where we don't JIT we fall back to any BLAS library. MKL is automatically used when being found. Cases in which we don't JIT high performance kernels: \sqrt[3]{MNK} > 80, transA/B != N, alpha != 1,0, beta != 0. Using the THRESHOLD parameter at compile time or libxsmm_dispatch the >80 limitation can be overcome.

Alex

**Comment by sidkashyap** [comment]
Thank you very much, I was trying to compare the performance between MKL and libxsmm, but I am afraid, I cannot get around beta != 0 (and the eventual call to MKL).

**Comment by alheinecke** [comment]
Sorry I had a typo, beta != 0,1 so if you have beta=1 that should be fine.

**Comment by hfp** [comment]
@sidkashyap How is your evaluation going?

I have looked into our "xgemm" sample code (benchmark), which was hanging on my system from time to time, and found it is related to OpenBLAS (if selected at link-time). Though our build system picks MKL, OpenBLAS, or the reference LAPACK/BLAS in this order (depending on what's available). I've tested OpenBLAS 0.2.18 with OpenMP and Pthread threading runtime ("o" and "p" variant respectively), and found a deadlock in the very first OpenBLAS GEMM call (prior to running anything else). Anyhow, this is a different story. However, such a severe issue is also able to screw up performance...

Now that one can disable running the validation (https://github.com/hfp/libxsmm/blob/master/samples/xgemm/xgemm.c#L46), I found the GOMP based performance is not too bad on my system (E5-2699v4). I tried other Xeon systems, and it looks similar (I haven't checked with desktop or mobile CPUs). I found big impact from affinity (as expected), and therefore one might run any benchmark with proper affinitization. One could simply use the xgemm.sh script (which is there since ever), or take care otherwise. Here is what I tested:

```
$ make -j ; cd samples/xgemm ; make
$ ./xgemm.sh 2000
```

Now this gives ~900 GFLOPS/s for DGEMM or ~1.85 TF/s for SGEMM (E5-2699v4, Turbo ON) when using GOMP via GCC 5.3.0, 5.4.0, or 6.2.0. However, with GCC 4.8.5 or GCC 5.2.0 it looks like you said: no scaling, no performance. Please also note, that the xgemm sample code does not perform many repeated calls by default (fluctuations due to Turbo are not averaged out). I recommend to pin the clock frequency for this benchmark, which then gives more repeatable performance even for singular calls.
